language: node_js
node_js: 
#  - stable
  - "8"
before_install:
  - export TZ='Asia/Shanghai'  # 设置时区
  - export GH_TAG="$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - git config --local user.name "beilly"
  - git config --local user.email "daben107@gmail.com"

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo g
  
after_success:
  - git tag ${GH_TAG}
  - tar -zcf ${TRAVIS_BUILD_DIR}-${TRAVIS_TAG}-$(GH_TAG)-${TRAVIS_BUILD_NUMBER}.tar.gz ./public 

deploy:   # 部署
  - provider: pages
    local_dir: ./public
    skip_cleanup: true 
    github_token: $GH_TOKEN # Set in travis-ci.org dashboard
    target_branch: master # 
    on:
      branch: source
  - provider: releases # 部署到GitHub Release，除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
    api_key:           # 填写GitHub的token （Settings -> Personal access tokens -> Generate new token）
      secure: $GH_TOKEN
    file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
    skip_cleanup: true     # 设置为true以跳过清理,不然apk文件就会被清理
    on:     # 发布时机           
      branch: source       


# E: Build LifeCycle

branches:
  only:
    - master
    - source

cache:
  apt: true
  directories:
    - node_module

env:
 global:
   - GH_REF: github.com/beilly/beilly.github.io.git
   