language: node_js
node_js: 
#  - stable
  - "8"
before_install:
  - export TZ='Asia/Shanghai'  # 设置时区

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo g

before_deploy:
  - git config --local user.name "beilly"
  - git config --local user.email "daben107@gmail.com"
  - git tag $(GH_TAG)
  
  - cd ./public
  - tar -zcf $(TRAVIS_BUILD_DIR)-${TRAVIS_TAG}-$(GH_TAG)-${TRAVIS_BUILD_NUMBER}.tar.gz ./*
deploy:              # 部署
  provider: releases # 部署到GitHub Release，除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  api_key:           # 填写GitHub的token （Settings -> Personal access tokens -> Generate new token）
    secure: ${GH_TOKEN}
  file: $(TRAVIS_BUILD_DIR)${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
  skip_cleanup: true     # 设置为true以跳过清理,不然apk文件就会被清理
  on:     # 发布时机           
    branch: source       # tags设置为true表示只有在有tag的情况下才部署

after_script:
  - cd ./public
  - git init
  - git config user.name "beilly"
  - git config user.email "daben107@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source

cache:
  apt: true
  directories:
    - node_module

env:
 global:
   - GH_REF: github.com/beilly/beilly.github.io.git
   - GH_TAG: $(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)
   